import { createSelector } from '@reduxjs/toolkit';
import { RootState } from './index';
import { tasksAdapter } from './tasksSlice';

// 1. Base tasks state selector
export const selectTasksState = (state: RootState) => state.tasks;

// 2. Selectors generated by entity adapter
const adapterSelectors = tasksAdapter.getSelectors(selectTasksState);

export const selectAllTasks = adapterSelectors.selectAll;

export const selectTaskEntities = adapterSelectors.selectEntities;
export const selectTaskIds = adapterSelectors.selectIds;

// 3. Selection and status selectors
export const selectTasksStatus = createSelector(
  selectTasksState,
  (tasks) => tasks.status
);

export const selectTasksError = createSelector(
  selectTasksState,
  (tasks) => tasks.error
);

export const selectPagination = createSelector(
  selectTasksState,
  (tasks) => tasks.pagination
);

// 4. Task selection selectors
export const selectSelectedTaskId = (state: RootState) => state.taskView.selectedTaskId;

export const selectSelectedTask = createSelector(
  selectTaskEntities,
  selectSelectedTaskId,
  (entities, id) => (id ? entities[id] || null : null)
);

export const selectSelectedTaskExists = createSelector(
  selectSelectedTask,
  (task) => task !== null
);
